### ISSUE TITLE
How can I train this model?

### ISSUE THREAD

**Issue by txw1997** [MinkiJ/SnaTCHer#1]
I found that there is only evaluation test in main.py, can I train a model in another dataset?

**Comment by MinkiJ** [comment]
Thank you for your interest.
Since our method does not require additional training modules for unseen detection, please refer to various few-shot learning methods to train models.
After training, refer [https://github.com/MinkiJ/SnaTCHer/blob/main/model/trainer/fsl_trainer_SnaTCHerF.py](https://github.com/MinkiJ/SnaTCHer/blob/main/model/trainer/fsl_trainer_SnaTCHerF.py) to use SnaTCHer.
